### PR TITLE
EZP-30229: Unlock Location visibility on hidden content

### PR DESCRIPTION
**Pull request by Nattfarinn**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-30229 (Alternative approach)
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

## Depends on: https://github.com/ezsystems/ezpublish-kernel/pull/2562

Screenshot 2019-03-14 at 11 27 12

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by micszo** [comment]
A thing that is inconsistent in the new approach is that when locations are made invisible (as in one at a time when the content items is visible and the parent is visible) the `Hidden by superior` message is still displayed.
Screen Shot 2019-03-25 at 12 34 27

**Comment by Nattfarinn** [comment]
@micszo Fixed

**Comment by micszo** [comment]
Observation. `Hidden by superior` is displayed for a location in both cases: when a content item is hidden, when the parent of a content item is hidden.

**Comment by Nattfarinn** [comment]
@micszo Fix ready, please retest

**Pull request merged**
