### PR TITLE
EZP-31692: Hide tooltip after show/hide details of content

### PR DESCRIPTION
**Pull request by lucasOsti**
jira ref: https://jira.ez.no/browse/EZP-31692

### CODE REVIEW

**Comment by dew326** [comment]
Is this valid for 3.0?

**Comment by lucasOsti** [comment]
> Is this valid for 3.0?

in 3.0 we don't have a title for button "question mark"

**Comment by dew326** [comment]
So the question is should we have a tooltip there?

**Comment by lserwatka** [comment]
You can merge it up.

**Pull request merged**
