### PR TITLE
EZP-28427: There is no red glow for a field when focused

### PR DESCRIPTION
**Pull request by sunpietro**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28428
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

The rich text field type validation will be implemented in another PR.

### CODE REVIEW

**Comment by sunpietro** [comment]
@barbaragr please, add steps to reproduce the issues you reported in the comment above.

**Comment by barbaragr** [comment]
Updated

**Comment by sunpietro** [comment]
I've just tested the reported fields. The glow for ezkeyword fieldtype appears. The only with no glow is ezselection fieldtype.

**Comment by sunpietro** [comment]
ping @barbaragr

**Comment by barbaragr** [comment]
Still no glow for keywords, I attached a mov file.
[glow2.zip](https://github.com/ezsystems/ezplatform-admin-ui/files/1559053/glow2.zip)

**Pull request merged**
