### PR TITLE
EZP-31542: Added PHP 7.4 support (eZ Platform 2.5)

### PR DESCRIPTION
**Pull request by adamwojs**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31542](https://jira.ez.no/browse/EZP-31542)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `1.5`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

#### Checklist:
- [X] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by adamwojs** [comment]
> Travis is failing (otherwise +1) ;)

Dependencies are installed from branches without PHP 7.4 support. I assumed that "Admin-UI tests on Clean P" and "Admin UI tests using different personas" are part of the regression suite. Is is correct @mnocon ?

**Comment by mnocon** [comment]
@adamwojs yep, that's right

**Comment by mnocon** [comment]
@adamwojs I'm getting `Notice: Trying to access array offset on value of type null` when trying to open the "Search" tab in AdminUI. Full error:
```
Symfony\Component\Debug\Exception\ContextErrorException:
Notice: Trying to access array offset on value of type null

  at vendor/ezsystems/ezplatform-admin-ui/src/bundle/Controller/SearchController.php:106
  at EzSystems\EzPlatformAdminUiBundle\Controller\SearchController->searchAction(object(Request))
```

Steps:
1. Login as admin
2. Go to Content -> Content structure
3. Click "Search"

BTW @micszo is experiencing the same thing on 3.0

**Comment by adamwojs** [comment]
> @adamwojs I'm getting Notice: Trying to access array offset on value of type null when trying to open the "Search" tab in AdminUI. Full error:

It looks like a related issue. I will check it!

**Pull request merged**
