### PR TITLE
EZP-31788: Remove duplicate icon from svg file

### PR DESCRIPTION
**Pull request by ITernovtsiy**
| Question      | Answer
| ------------- | ---
| Tickets       | [EZP-31788](https://jira.ez.no/browse/EZP-31788)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

There are duplicate "portfolio" icons in `ez-icons.svg`, removing the oldest one.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by adamwojs** [comment]
Indeed `portfolio` id is duplicated but I will leave decision to frontend team :wink:

**Comment by dew326** [comment]
I see this also affects the 2.5. Could you rebase to 1.5 branch?

**Comment by ITernovtsiy** [comment]
Rebased to 1.5

Duplicate IDs lead to icons not displayed in chrome.
I can reproduce it only on edit page, and only when chrome loading file from disk cache, and only if page opened from a non-admin domain.
Screenshot from 2020-08-06 12-34-31

I manually replaced file to the one I have in PR, and can't reproduce chrome issue anymore.
After I replaced it back to "broken" icons file, I can reproduce it again.
So, I'm sure it's related to "portfolio" icon duplicated.

**Comment by dew326** [comment]
Thanks for sharing the details of the issue.
We would merge it anyway, but I only wanted to merge it with the proper version.

We have spotted the issue with missing icons in some rare cases but didn't investigate it more yet. I think you saved us a lot of time debugging this. Thanks a lot.

**Comment by adamwojs** [comment]
Thank you for contribution @ITernovtsiy!

**Pull request merged**
