### PR TITLE
EZP-29654: No margin at the bottom of the page on Safari

### PR DESCRIPTION
**Pull request by sunpietro**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29654
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

### CODE REVIEW

**Comment by barbaragr** [comment]
For dev env looks fine only with symfony toolbar:
screen shot 2018-09-28 at 14 49 35
When it is hidden, there is no margin:
screen shot 2018-09-28 at 14 49 44

**Comment by sunpietro** [comment]
This is unrelated to any environment. Please, clear cache on the server and in the browser. @micszo can you help here?

**Comment by micszo** [comment]
Sure, let me see...

**Comment by sunpietro** [comment]
ping @barbaragr

**Pull request merged**
