### PR TITLE
EZP-28759: eZ Design Engine support

### PR DESCRIPTION
**Pull request by emodric**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28759
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | kinda
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

This adds proper full support for eZ Design Theme Engine. Also adds the possibility to parametrize the pagelayout template to enable simple overriding for customized/stripped down admin interfaces.

Depends on: https://github.com/ezsystems/ezplatform/pull/255

Potential BC break would be if someone used deprecated Twig templates syntax `BundleName:path:template.html.twig` to reference to templates from admin UI.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by emodric** [comment]
Not sure why Behat build is failing, I've specified by ezplatform repo fork with the needed branch.

**Comment by lserwatka** [comment]
@emodric thank you for your work on this. Could you re-base with latest changes, we will slowly start evaluating this PR and do proper QA on top of it.

**Comment by emodric** [comment]
@lserwatka Done.

**Comment by alongosz** [comment]
Closing in favor of #467

**Pull request closed without merging**
