### PR TITLE
EZP-28932: Broken empty option design after selecting it from ezselection fieldtype

### PR DESCRIPTION
**Pull request by sunpietro**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28932
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

### CODE REVIEW

**Comment by sunpietro** [comment]
ping @dew326 @barbaragr 
Please, test with long text examples in the options labels.

**Comment by barbaragr** [comment]
If I had two the same options, for example: `abc`, only one of them is show in creation form. Should we allow user to add identical options then?

**Comment by sunpietro** [comment]
@barbaragr  I believe it's a question to PMs. Currently, it's out of scope of this PR.
cc @SylvainGuittard

**Comment by SylvainGuittard** [comment]
Regarding identical options, I agree with @sunpietro: it's out of scope of this PR.
I think not allowing the user to use the identical labels for option is a good idea. I also don't think this will happen in a real use case. So, no need for a follow up story.

**Pull request merged**
