### PR TITLE
EZP-32212: Changed class to correct recognition ezmatrix fieldType

### PR DESCRIPTION
**Pull request by mateuszdebinski**
| Question      | Answer
| ------------- | ---
| Tickets       | [EZP-32212](https://issues.ibexa.co/browse/EZP-32212)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Related PR: https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/45
Passed tests: https://travis-ci.com/github/ezsystems/ezplatform-page-builder/builds/207258337 

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Review by konradoboza — APPROVED** [review]

**Review by mnocon — CHANGES_REQUESTED** [review]
Q: Why is this diff different from the current state of this file in 1.5 branch?
https://github.com/ezsystems/ezplatform-admin-ui/blob/1.5/src/lib/Behat/PageElement/ContentField.php#L46-L63
There's a condition missing for ezuser.

Ezmatrix tests will now share the same selector with ezmatrix and the one for ezmatrix will be more generic, so the condition for ezuser should be first, something like this should be ok:
```
    private function getFieldTypeIdentifier(string $fieldClass): string
    {
        if ($fieldClass === '') {
            return 'ezboolean';
        }

        if ($fieldClass === 'ez-scrollable-table-wrapper mb-0') {
            return 'ezuser';
        }

        if (strpos($fieldClass, 'ez-scrollable-table-wrapper') !== false) {
            return 'ezmatrix';
        }

        preg_match($this::FIELD_TYPE_CLASS_REGEX, $fieldClass, $matches);
        $matchedValue = explode('-', $matches[0])[0];

        return $matchedValue;
    }
```

**Comment by mateuszdebinski** [comment]
> Q: Why is this diff different from the current state of this file in 1.5 branch?
> https://github.com/ezsystems/ezplatform-admin-ui/blob/1.5/src/lib/Behat/PageElement/ContentField.php#L46-L63
> There's a condition missing for ezuser.
> 
> Ezmatrix tests will now share the same selector with ezmatrix and the one for ezmatrix will be more generic, so the condition for ezuser should be first, something like this should be ok:
> 
> ```
>     private function getFieldTypeIdentifier(string $fieldClass): string
>     {
>         if ($fieldClass === '') {
>             return 'ezboolean';
>         }
> 
>         if ($fieldClass === 'ez-scrollable-table-wrapper mb-0') {
>             return 'ezuser';
>         }
> 
>         if (strpos($fieldClass, 'ez-scrollable-table-wrapper') !== false) {
>             return 'ezmatrix';
>         }
> 
>         preg_match($this::FIELD_TYPE_CLASS_REGEX, $fieldClass, $matches);
>         $matchedValue = explode('-', $matches[0])[0];
> 
>         return $matchedValue;
>     }
> ```

corrected, I have forgotten git pull before creating this branch

**Review by mnocon — APPROVED** [review]
Thanks!

**Review by mateuszbieniek — APPROVED** [review]

**Review by bogusez — APPROVED** [review]

**Comment by adamwojs** [comment]
Could you please merge up changes @mateuszdebinski ?

**Pull request merged**
