### PR TITLE
EZP-32054: Search view is inconsistent with other main views

### PR DESCRIPTION
**Pull request by lserwatka**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-32054
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes/no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Comment by dew326** [comment]
Behat is failing and it seems related.

**Comment by lserwatka** [comment]
@mnocon could you adjust Behat tests?

**Comment by lserwatka** [comment]
Thank you @mnocon Let's see if passes after your fix.

**Comment by mnocon** [comment]
@lserwatka it's green 🎉

**Pull request merged**
