### PR TITLE
EZP-29328: As an editor I want AE to support formatted text

### PR DESCRIPTION
**Pull request by dew326**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29328
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

**Screenshot:**
formatted

This is a new feature but the target branch is 1.3 as this is needed for the migration.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by dew326** [comment]
@andrerom yes, it's because the empty `pre` tag gets some empty text nodes. Hopefully it's fixed in this line: https://github.com/ezsystems/ezplatform-admin-ui/pull/709/files#diff-71c5e1a664b1342cfae2e62de8b241bbR19

**Comment by katarzynazawada** [comment]
After fixes:

- Pre use scroll is not added on Firefox 

- Cursor is outside the block frame on Safari

1. Click on Rich Text Editor
2. Change style to Formatted.
3. Type same text.
4. Add new block (Paragraph).
5. Change Paragraph style to Formatted.
6. Change the style back to Paragraph.

screenshot 2018-11-13 at 08 47 02

**Comment by dew326** [comment]
@katarzynazawada 
As discussed in private first issue is because "lorem ipsum" copy paragraph with styles and we cannot do anything with that. If the text is unstyled or typed into the field the scroll is added.

The second issue is not related to our code base. I can reproduce the issue on AlloyEditor demo. I created an issue for AE devs: https://github.com/liferay/alloy-editor/issues/902

**Comment by lserwatka** [comment]
@dew326 you can merge it up

**Pull request merged**
