### PR TITLE
EZP-28660: Top menu is not adding sections when there is no children which breaks extensibility

### PR DESCRIPTION
**Pull request by webhdx**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28660
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by emodric** [comment]
This broke Netgen Tags top menu item somehow :(

**Comment by emodric** [comment]
Probably because of added `if item.children|length > 0` in the template.

**Comment by webhdx** [comment]
@emodric I see. Fix incoming. Sorry ;)

**Comment by emodric** [comment]
@webhdx Thanks for the quick reaction :)

**Comment by webhdx** [comment]
@emodric https://github.com/ezsystems/ezplatform-admin-ui/pull/288

**Pull request merged**
