### PR TITLE
Remove Alloy Editor dist folder, as it is not used because of Webpack Encore

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
| Question      | Answer
| ------------- | ---
| Tickets       | N/A
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

There is no need to have `dist` folder for Alloy Editor.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by lserwatka** [comment]
@dew326 is this valid?

**Comment by dew326** [comment]
Yes, this is valid for master, in 2.5 we need to keep those files.

**Comment by SerheyDolgushev** [comment]
@dew326 sorry, you mean we **do not** need to keep those files. Please correct me if I'm wrong.

**Comment by dew326** [comment]
We need those files in 2.5 for backward compatibility, someone could include AlloyEditor in own twig as we had in 2.4 in Richtext block in Page Builder. If we remove those files in 2.5 we would break their project. 

We can safely remove it from 3.0.

**Comment by SerheyDolgushev** [comment]
@dew326 you are correct. Wasnt thinking about that. Does it mean we should close this PR for now?

**Comment by lserwatka** [comment]
Yes, and we will take over on removing it later from 3.0 release.

**Pull request closed without merging**
