### PR TITLE
EZP-29663: Login page redirects to notifications/count

### PR DESCRIPTION
**Pull request by ViniTou**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29663
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by ViniTou** [comment]
Is there a correct way for us to apply this globally for every request?

**Comment by ViniTou** [comment]
Hint for QA:

I opened two tabs, both on dashboard. Then logout on one and go to /admin first (not /admin/login). Then on second tab you should have two request every 30 seconds - count and login. Try to login then on the first tab, and you should be redirected to json from /notification/count.

**Comment by andrerom** [comment]
So we rely on session for redirect or?
If so, that is to ask for problems :)

**Comment by ViniTou** [comment]
@andrerom 
that's how symfony does it.

**Comment by andrerom** [comment]
ok

**Comment by ViniTou** [comment]
Yes, thought about it right now, definitely we could try this but in separate PR.

**Pull request merged**
