### PR TITLE
IBX-737: Disabled buttons in Context Menu should be purple instead of grey

### PR DESCRIPTION
**Pull request by tischsoic**
| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-737
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Issue: https://github.com/ezsystems/ezplatform-admin-ui/pull/1785#issuecomment-875678323

# After fix
Screenshot 2021-07-08 at 08 28 23

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Review by GrabowskiM — APPROVED** [review]

**Review by dew326 — APPROVED** [review]

**Comment by lserwatka** [comment]
Love it! Let's merge it.

**Review by piotrbisaga — APPROVED** [review]
QA Approved.
Checked on Ibexa Commerce 3.3.6-dev with .diff
Checked on Chrome & Firefox.

**Comment by lserwatka** [comment]
You can merge it up now.

**Comment by tischsoic** [comment]
Merged up:
- 2.3: https://github.com/ezsystems/ezplatform-admin-ui/commit/fb424d56aa96045c5e7a563233cf14a53e2157ea

**Pull request merged**
