### PR TITLE
EZP-30359: Override Content Tree module root for Users, Media, Forms locations

### PR DESCRIPTION
**Pull request by webhdx**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-30359
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

# Description
This PR adds new setting to the Content Tree Module:
```yaml
# ...
        admin_group:
            content_tree_module:
                # ...
                tree_root_location_id: 1
                contextual_tree_root_location_ids:
                    - 2 # Home
                    - 5 # Users
                    - 43 # Media
                    - 249 # Forms
```

New `contextual_tree_root_location_ids` setting allows to provide a list of Location IDs for which content tree's root location will be changed. With above configuration snippet (EE demo) tree root is overrode for Content structure, Media, Users and Forms tabs:
image

ping @ezsystems/documentation-team - it needs to be added to the doc.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by lserwatka** [comment]
@webhdx where shall we add those default settings?

**Comment by webhdx** [comment]
Default configuration has to be added to meta repositories as it will be different for clean/demo, OSS/EE. I'm working on those right now.

**Comment by lserwatka** [comment]
Awesome!

**Comment by SylvainGuittard** [comment]
Very good job @webhdx !
Really appreciated 👍

**Comment by webhdx** [comment]
I had to do little refactoring in `ContentViewController` (https://github.com/ezsystems/ezplatform-admin-ui/pull/928/commits/ead6fd11e96360135946ecff5932c5019df586ee) as number of arguments in the constructor was way too big. All properties based on parameters were replaced by `ConfigResolver::getParameter` call.

cc @Nattfarinn @ViniTou @adamwojs @pawbuj @mikadamczyk

**Comment by webhdx** [comment]
Related PR: https://github.com/ezsystems/ezplatform/pull/379

**Comment by lserwatka** [comment]
Well done!

**Pull request merged**
