### PR TITLE
EZP-30308: User menu changes width depending on user name length

### PR DESCRIPTION
**Pull request by tischsoic**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-30308
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

### After fix:
Screen Shot 2019-03-18 at 08 10 56

### CODE REVIEW

**Comment by barbaragr** [comment]
For really short username user menu still changes its width a little. Are we ok with that?
Screen Shot 2019-03-18 at 16 42 35

**Comment by lserwatka** [comment]
We can set some min width so that all labels remains in a single line.

**Comment by tischsoic** [comment]
I missed this, I've added _white-space: nowrap_. ping @barbaragr 🙂 
Screen Shot 2019-03-19 at 04 07 12

**Comment by tischsoic** [comment]
Merged up:
- master: https://github.com/ezsystems/ezplatform-admin-ui/commit/c538e51c076d0cddb2cc1e408da875e0b1d82d55

**Pull request merged**
