### PR TITLE
EZP-32287: Wrong size of a Save tile on the URL management edit page

### PR DESCRIPTION
**Pull request by lucasOsti**
| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/EZP-32287
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Added missing html container `.ez-sticky-container`

Screenshot from 2021-01-15 14-59-17

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Review by GrabowskiM — APPROVED** [review]

**Review by bogusez — APPROVED** [review]

**Comment by bogusez** [comment]
Please do not marge yet

**Comment by bogusez** [comment]
We need PR for 3.2 version as well

**Comment by lserwatka** [comment]
What happened here? Can't we change target brach to 3.2 and rebase?

**Comment by bogusez** [comment]
> What happened here? Can't we change target brach to 3.2 and rebase?

A new PR to 3.2 has been made by @lucasOsti

**Comment by bogusez** [comment]
> @bogusez Ok, so can we merge this one?

Yes, we can merge it to master

**Pull request merged**
