### PR TITLE
IBX-759: Fixed wrong class taken to calculate toolbar's width

### PR DESCRIPTION
**Pull request by konradoboza**
| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-759](https://issues.ibexa.co/browse/IBX-759)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Followup for https://github.com/ezsystems/ezplatform-richtext/pull/196 targetting eZ Platform 2.5.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Review by tischsoic — APPROVED** [review]

**Review by GrabowskiM — APPROVED** [review]

**Review by piotrbisaga — APPROVED** [review]
QA approved.
Checked on eZ Platform Enterprise  2.5-dev with .diff

**Comment by dew326** [comment]
@konradoboza you can merge it up

**Comment by YohannsMonnier** [comment]
Dear guys, We also have the same issue in Ibexa 3.3.6

Could you please push the fix to the last version ? 

Yohann

**Comment by dew326** [comment]
Hi @YohannsMonnier, this fix was introduced after the 3.3.6 was released as far I can see.
This will be included in the next LTS patch release 3.3.7.

**Comment by sleguevaques** [comment]
Hi @dew326, 
Do you have any idea when the patch 3.3.7 will be released?

**Comment by dew326** [comment]
Hi @sleguevaques, 3.3.7 is scheduled for the end of next week.

**Pull request merged**
