### PR TITLE
EZP-32333: Hidden duplicated 'change password' menu item

### PR DESCRIPTION
**Pull request by barw4**
| Question      | Answer
| ------------- | ---
| Tickets       | [EZP-32333](https://jira.ez.no/browse/EZP-32333)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

This fragment is not needed here as this menu item is generated in `ezplatform-user` package nevertheless:  https://github.com/ezsystems/ezplatform-user/blob/1.0/src/lib/EventListener/UserMenuListener.php#L49

Related `ezplatform-user` PR: https://github.com/ezsystems/ezplatform-user/pull/92

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Review by ViniTou — APPROVED** [review]
Just remeber when merging up, that UserMenuListener is no longer in ezplatform-user, and it was moved back to adminUI (and as I see now, it should be removed also there and that functionality should be restored here).

**Review by adamwojs — APPROVED** [review]

**Review by kacper-wieczorek-ibexa — APPROVED** [review]
QA - Approved. Tested on 2.5.18

**Comment by adamwojs** [comment]
Could you please merge up changes @barw4 ?

**Comment by barw4** [comment]
Merged into:
`2.2`: https://github.com/ezsystems/ezplatform-admin-ui/commit/d30d62701df00dff9c981704052ed923d3932f82
`2.3`: https://github.com/ezsystems/ezplatform-admin-ui/commit/6d9a1aac946c45b1fce466280ad1d38f34a71f85
`master`: [WIP]

**Pull request merged**
