### PR TITLE
Missed reference to location_ids.content (EZP-28553)

### PR DESCRIPTION
**Pull request by wizhippo**
EZP-28553: Adds Permission Awareness to all menus

| Question      | Answer
| ------------- | ---
| Tickets       | Related to EZP-28553
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

### CODE REVIEW

**Comment by emodric** [comment]
Why are these IDs (for media and users section) even defined here? Shouldn't they be taken from eZ kernel?

**Comment by webhdx** [comment]
@emodric These settings are not available in kernel.

**Comment by emodric** [comment]
My bad, sorry :)

**Comment by andrerom** [comment]
yup, they probably should be :) _(but then installer will need to modify them depending on installed demo content, in case of future multi page demo)_

**Pull request merged**
