### PR TITLE
Fixed: copyright footer position

### PR DESCRIPTION
**Pull request by patrickallaert**
Picture of the problem: 
image

| Question      | Answer
| ------------- | ---
| Tickets       | N/A
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by dew326** [comment]
Hi, could you say more about the issue? How to reproduce it?

**Comment by patrickallaert** [comment]
> Hi, could you say more about the issue? How to reproduce it?

Simply use ibexa/oss, go to the admin interface and go to a page that is long enough to have a vertical lift.
You will see the footer in the middle of the page, see screenshot.

**Comment by dew326** [comment]
Sorry, we cannot reproduce the issue, we tested this on OSS 3.3.3.

Can you provide information about:
-  ibexa/oss version
- Browser version
- OS version
- Does it affect the whole of the application or just some specific content in content structure?

**Comment by patrickallaert** [comment]
> Sorry, we cannot reproduce the issue, we tested this on OSS 3.3.3.

We discussed that issue on eZ Community slack general channel. I think @emodric can confirm he has the issue, @wizhippo for sure too as he provided similar screenshot than the one in the description.

I guess it has been introduced in 8ff773308891d2da9dd9806390372623022c007d.

> Can you provide information about:
> 
> * ibexa/oss version

3.3.3

> * Browser version

Confirmed on both Chromium 90, Chrome 91 and Firefox 89.0.

> * OS version

Linux, but not relevant.

> * Does it affect the whole of the application or just some specific content in content structure?

Anywhere in the admin where that footer is visible and where the content of the page doesn't fit on one screen.

**Comment by emodric** [comment]
Yep, I can confirm the issue on Ibexa OSS 3.3.4. Another screenshot:

image

**Comment by patrickallaert** [comment]
Seems to happen because of Netgen/TagsBundle, as mentioned by @konradoboza in slack, more precisely: https://github.com/netgen/TagsBundle/blob/master/bundle/Resources/sass/admin/_base.scss#L2-L5

**Comment by dew326** [comment]
Closed as this should be fixed in Netgen/TagsBundle.

**Pull request closed without merging**
