### PR TITLE
EZEE-30310: SearchLimit UDW: UDW search limit configuration in YAML

### PR DESCRIPTION
**Pull request by czechmarcin**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-30310
| Bug fix?      |no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

This PR goes along with https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/160

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by konradoboza** [comment]
As this is a new feature, shouldn't it be targeted to master?

**Comment by lserwatka** [comment]
@konradoboza it is small enough, we can make it for 1.4.

**Comment by micszo** [comment]
To be reported separately: Copy Subtree does not use `data-udw-config`.

**Comment by lserwatka** [comment]
Could you merge it up?

**Comment by czechmarcin** [comment]
commit ca034805c9e63984bfb8880604337c5e51b10768 (HEAD -> master, upstream/master)
Merge: a92dc219 ca3678ae
Author: Dawid Parafiński <dawid.parafinski@ez.no>
Date:   Mon Mar 18 16:30:51 2019 +0100

    Merge branch '1.4' of github.com:ezsystems/ezplatform-admin-ui

**Already merged.**

**Pull request merged**
