### PR TITLE
EZP-29856: Expose form's data ContentCreateStruct in content create view

### PR DESCRIPTION
**Pull request by webhdx**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29856
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by lserwatka** [comment]
@mnocon travis is failing here.

**Comment by lserwatka** [comment]
@micszo we only need sanities here

**Comment by mnocon** [comment]
@lserwatka @webhdx PHPUnit is failing, a test called `EzSystems\EzPlatformAdminUi\Tests\RepositoryForms\View\ViewParametersListenerTest::testSubscribedEvents`

**Comment by webhdx** [comment]
@mikadamczyk Fixed according to your review.

@mnocon & @micszo Should be now green on Travis.

**Pull request merged**
