### PR TITLE
EZEE-1878: Design update - Icons review and update

### PR DESCRIPTION
**Pull request by inakijv**
| Question      | Answer
| ------------- | ---
| Tickets       | 
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

**Optimized icons set**

**Icons reviewed:**
edit, restore-parent, trash, archive-restore, subscript, lock, fields, content-list, upload, download, bubbles, list-numbered, list, options, align-left, align-right, align-center, align-justify, portfolio, versions, h1, h3, drag.

**Icons added:**
back, lock-unlocked, core, b2b, cart, cart-upload, cart-wishlist, customer, order-management, mail, rate-review, erp, slider, slider-lastviewed, components, newsletter, about-info, settings-config, logout, profile, h2, h3, h4, h5, h6, bestseller, server, languages-add, custom_tags, twitter, bookmark, bookmark-active, bookmark-manager, layout-switch.

(Note: Added optimized icons in two different commits to better manage which ones are the reviewed ones and which ones the new additions.)

screen shot 2018-02-16 at 2 45 17 am

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by sunpietro** [comment]
I'm not sure if we should update existing icons after releasing 2.0 stable version. I might be wrong, but changing the icons in this major version is like changing icons used by Windows 7 to icons used by Windows 10 (after releasing Win7). Do you agree? 
Adding new icons is OK. I'm just unsure about changing the existing ones.
Furthermore, to better visualize what has changed, it would be good to prepare a comparison table with a state before and a state after changes.

**Comment by inakijv** [comment]
I understand your concern @sunpietro and see your point, but the review is based on the need of improving their design according to the rendering we are getting (in most of the cases included) or aligning them based on the design of others similars to them
(Just for clarification purposes, I don't see a design line change here. I am proposing an improvement to some of the existing ones and adding new ones needed).
I'll add the comparison table you ask.

**Comment by sunpietro** [comment]
@inakijv thank you :)

**Comment by inakijv** [comment]
icons_review_table

Ping @sunpietro

**Comment by lserwatka** [comment]
@inakijv I had to revert your commit. So many icons were missing after this change. Could you double-check it and make sure everything works as expected?

**Pull request merged**
