### PR TITLE
EZP-28598: Fixes no filtering langauge on create content UI

### PR DESCRIPTION
**Pull request by webhdx**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28598
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

### CODE REVIEW

**Comment by micszo** [comment]
@webhdx it is intentional that error 500 is thrown when the two `languages` arrays in ezplatform.yml are not identical?
screen shot 2017-12-19 at 10 35 09
(one is in system: site_group: and the other in system: admin_group:)

**Comment by micszo** [comment]
Also on this branch with a testeditor user I cannot enter Content / Content structure with a set o policies that allow that on _master_.
screen shot 2017-12-19 at 11 06 08
The policies are:
screen shot 2017-12-19 at 11 08 13

**Comment by micszo** [comment]
@webhdx could you confirm the necessary policies for a editor limited to one language?

**Comment by lserwatka** [comment]
@webhdx rebase is needed

**Comment by micszo** [comment]
@mnocon we reached a deadlock, please help. I still have the second error which Maciek cannot reproduce.

**Comment by micszo** [comment]
List of policies from Maciek:
image

**Comment by mnocon** [comment]
@micszo @webhdx  looks like it works for me - I have created a French language, created a user that is assigned to the Role specified above and I can browse Content -> Content Structure on ezplatform-ee (dev mode). We can go through that tomorrow to double check everything.

**Comment by webhdx** [comment]
Ok, I managed to reproduce the issue. It's caused by `PermissionResolver`:
1. In `canUser()` it overrides `$targets = null` when `$targets` is empty. Later when it checks `SubtreeLimitation`  it expects `$targets` to be an array.

cc @alongosz

**Comment by webhdx** [comment]
Further investigation: Whole PR won't work:
In order to check permissions I have to create `ContentCreateStruct` simulating content user is going to create. In case we are not able to provide ContentType information which is required to perform Permissions check.

For the time being we can only limit language list depending on siteaccess defined languages.

**Comment by micszo** [comment]
Follow-up improvement https://jira.ez.no/browse/EZP-28620.

**Pull request merged**
