### PR TITLE
EZP-29650: [Content Type Fields] Selection field UI issues

### PR DESCRIPTION
**Pull request by tischsoic**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29650
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Fixes color of arrow in Selection field.

screen shot 2018-09-26 at 15 15 28

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by barbaragr** [comment]
One more thing is missed:
`The field changes the appearance of the cursor (from arrow to finger) over the whole width of the form, not only when it is actually hovering the field.`
screen shot 2018-09-27 at 15 45 12

**Comment by sunpietro** [comment]
The dropdown arrow issue has been already fixed in #650

**Comment by barbaragr** [comment]
EZP-29650 contains two issues: dropdown arrow and  changing of cursor appearance. Are they both fixed by #650?

**Comment by sunpietro** [comment]
This PR was fixing only the issue with an arrow.

**Comment by barbaragr** [comment]
Yes, that's why I've written that one more thing is missed and @tischsoic promised to fixed it. That's why I'm asking :)

**Pull request closed without merging**
