### PR TITLE
EZP-30491: Design fix for "Conflict when hiding content item" modal

### PR DESCRIPTION
**Pull request by tischsoic**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-30491
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

### New look
Screen Shot 2019-09-04 at 14 41 09

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
@tischsoic Could you please change the sentence. Kind of missed it on the previous PR ;)

**Comment by tischsoic** [comment]
I updated information from modal, please check last commit @SylvainGuittard. :)

**Comment by lserwatka** [comment]
You can merge it up.

**Comment by tischsoic** [comment]
merged up with other PR:
- master: https://github.com/ezsystems/ezplatform-admin-ui/commit/0f1a833efc8a0344e49822b651ee3e8453497a0d

**Pull request merged**
