### PR TITLE
[EZP-28255]: Updated UI Icons 8px stroke

### PR DESCRIPTION
**Pull request by inakijv**
Most important aspects:
- Added new set of icons with 8px stroke;
- New icons added (including for Rich Text Editor): _history, list-numbered, superscript, subscript, strikethrough, restore-parent, quote, restore, timeline, table-cell, table-column, table-row, circle-caret-back, circle-caret-next, circle-caret-up, circle-caret-down_.
- Icons removed (not going to be used): _global-content, global-eztags, global-page, global-performance, shuffle, translation, recommended_.

ez platform
screen shot 2017-11-16 at 4 46 41 pm

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
Also new icons added: `circle-caret-*` :)

**Comment by SylvainGuittard** [comment]
Thanks @inakijv for compressing the icons, the world will thank you :) 🌎  
We can go further and remove `<!-- Generated by IcoMoon.io -->` ;)

**Comment by inakijv** [comment]
Reviewed. Thanks @SylvainGuittard

**Comment by dew326** [comment]
I run this on my local installation and it looks awesome. Great job @inakijv.

I will update the icons in the richText once this is merged.

I also found that there are missing two icons (maybe the name was changed).
- icon named `panel` was used for the icon of the admin in navigation
- icon named `embed` was used in richText to embed content

**Comment by lserwatka** [comment]
@inakijv could you make a JIRA ticket and amend commit message?

**Comment by inakijv** [comment]
Hi @dew326 thanks for the comment! I have checked _master_ and my _PR_ and you are right. These two icons are not included, but they are not because the _PR_ is done according to the final design approved. Hence, no icons are used in top `<navbar>`, that includes Admin panel link too (so that's why is out, but you are right I forgot to mention that). Regarding _embed_ icon, we have an inherited way of labeling icons, that `embed.svg` was designed for eZ Tags section months ago. The one that goes for the Rich Text Editor when embedding is `tag.svg`, that it's included. 

Hope this helps and clarifies the doubts generated.

**Comment by lserwatka** [comment]
@dew326 could you address those changes before beta, so that we can merge it?

**Comment by dew326** [comment]
@lserwatka commit pushed to this branch. 
- updated icons in richtext
- removed icons from navigation menu

**Pull request merged**
