### PR TITLE
EZP-28004: Hide or show location of content item.

### PR DESCRIPTION
**Pull request by mikadamczyk**
- https://jira.ez.no/browse/EZP-28004

Editor can hide and show a location of a content item. 

**Screencast:**
show-hidden-location

**TODO:**
- [x] rebase with master and recompiling css
- [x] hide checkbox in form
- [x] check missing translations

### CODE REVIEW

**Comment by dew326** [comment]
I also find a bug. If I set visibility to hidden for the home I'm redirected to the `/content/location/1` and this is throwing 404.

**Comment by lserwatka** [comment]
@dew326 could you make a followup bug in JIRA and assign it to @mikadamczyk

**Comment by lserwatka** [comment]
@m-tyrala Could you test this one now?

**Comment by mikadamczyk** [comment]
@lserwatka @dew326 this bug is already fixed. @m-tyrala could you check this?

**Comment by lserwatka** [comment]
@mikadamczyk I guess you have to include also translations?

**Comment by mikadamczyk** [comment]
The first screencast is without translations, but second is correct. I think all translations are included. #[https://github.com/ezsystems/ezplatform-admin-ui/pull/76/files#diff-91b9d2f1b40727821663bacbb61a14fc](url)

**Comment by lserwatka** [comment]
@mikadamczyk screen shot was confusing. If it is there, then all is good.

**Pull request merged**
