### PR TITLE
IBX-664: changed desc for pagination.viewing trans

### PR DESCRIPTION
**Pull request by mateuszdebinski**
| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-664](https://issues.ibexa.co/browse/IBX-664)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by dew326** [comment]
I think 3.3 is also affected, this should be merged to 2.3 branch.

**Comment by mateuszdebinski** [comment]
> I think 3.3 is also affected, this should be merged to 2.3 branch.

Yes, my mistake, I forgot to change the branch to correct, now changes to 2.3

**Review by dew326 — APPROVED** [review]

**Review by konradoboza — APPROVED** [review]

**Review by tischsoic — APPROVED** [review]

**Comment by bogusez** [comment]
Screenshot 2021-07-01 at 08 35 58

As discussed with Mateusz, it will be fixed in different task / pull request.

**Comment by mateuszdebinski** [comment]
> Screenshot 2021-07-01 at 08 35 58
> 
> As discussed with Mateusz, it will be fixed in different task / pull request.

This problem looks like an older fixed issue: https://issues.ibexa.co/browse/EZP-29674

**Review by bogusez — APPROVED** [review]

**Comment by lserwatka** [comment]
You can merge it up.

**Pull request merged**
