### PR TITLE
EZP-29973: Deleting content modal inconsistency

### PR DESCRIPTION
**Pull request by tischsoic**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29973
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

## New look

Screen Shot 2019-09-17 at 10 11 44

Screen Shot 2019-09-20 at 15 37 34

Screen Shot 2019-09-20 at 15 58 01

### CODE REVIEW

**Comment by inakijv** [comment]
bulk_delete_commented

Confirmation checkbox & text should have left spacing (margin or padding)

**Comment by tischsoic** [comment]
New look, @inakijv 

Screen Shot 2019-09-17 at 10 11 44

**Comment by tischsoic** [comment]
@barbaragr I found another related modal - for Image Asset with asset which belongs to 2 or more image assets fields:

Screen Shot 2019-09-20 at 15 58 01

**Comment by lserwatka** [comment]
@tischsoic could you merge it up?

**Comment by tischsoic** [comment]
Merged up (with other PR):
- master: https://github.com/ezsystems/ezplatform-admin-ui/commit/964827b563cbc0577b5a3bc013fb4bde943604a7

**Pull request merged**
