### PR TITLE
EZP-31583: Fixed views for Content without Location

### PR DESCRIPTION
**Pull request by barw4**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31583
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Some twig views have been tweaked to support `Contents` without `Locations`.

PR is a direct continuation of https://github.com/ezsystems/ezplatform-admin-ui/pull/1353, but for eZ Platform v3.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by micszo** [comment]
Orange pencil Edit button is available in Search results for item without location.

**Comment by barw4** [comment]
@micszo resolved in: https://github.com/ezsystems/ezplatform-admin-ui/pull/1402/commits/8625485850c900f5c8bad3c7cb8893fb43d37779

**Comment by lserwatka** [comment]
@barw4 could you merge it up?

**Comment by barw4** [comment]
Merged: https://github.com/ezsystems/ezplatform-admin-ui/commit/cd3f1bfe885a8a5ca13f0b68416c613161bc4372

**Pull request merged**
