### PR TITLE
EZP-28945: User will be able to search for content items by just selecting the filters.

### PR DESCRIPTION
**Pull request by mikadamczyk**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28945
| Bug fix?      |no
| New feature?  | yes
| BC breaks?    |no
| Tests pass?   | yes
| Doc needed?   |no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

User should be able to search for content items by just selecting the filters and applying the changes.

screen shot 2018-03-20 at 10 51 53 am

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

### CODE REVIEW

**Comment by dew326** [comment]
As searchQuery is now non-required so if some just hit search button without setting anything he will get all contents?

**Comment by mikadamczyk** [comment]
@dew326 yes, but thanks to pagination this should not be performance issue. That was the purpose of the task.

**Comment by alongosz** [comment]
Only one question: have you tested this with Solr? :)

**Comment by mikadamczyk** [comment]
@alongosz yes :) it gives the same results

**Pull request merged**
