### PR TITLE
EZP-31008: Move repository-forms code to ezplatform-admin-ui package

### PR DESCRIPTION
**Pull request by webhdx**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31008
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

### CODE REVIEW

**Comment by MarioBlazek** [comment]
Why?

**Comment by emodric** [comment]
This is a huge BC break for every 3rd party bundle out there implementing a custom field type.

**Comment by Nattfarinn** [comment]
That is why it is going to be part of `3.0`

**Comment by alongosz** [comment]
Yes, it's a BC break as stated in the PR description. It follows SemVer rules.

**Comment by emodric** [comment]
> That is why it is going to be part of `3.0`

> Yes, it's a BC break as stated in the PR description. It follows SemVer rules.

That's not the point. The point is that it becomes increasingly hard to maintain bundles that could otherwise be compatible with eZ Platform 2.5 and 3.0.

**Comment by MarioBlazek** [comment]
I know it is documented as BC break, but please don't do this. Is it really necessary?

**Comment by webhdx** [comment]
Repository Forms was only used as a provider for content edit functionality in AdminUI and there were many voices that it isn't really what people want for UGC solution. We want to come up with a better solution in the future. Realistically you only need to fix a few namespaces in you code. Do not make a huge deal out of it :)

**Comment by Nattfarinn** [comment]
>  The point is that it becomes increasingly hard to maintain bundles that could otherwise be compatible with eZ Platform 2.5 and 3.0.

Considering the scope of our changes for 3.0 in general, I'm afraid this PR changes nothing in regards to keeping bundle compatible with both version.

**Comment by emodric** [comment]
> Considering the scope of our changes for 3.0 in general, I'm afraid this PR changes nothing in regards to keeping bundle compatible with both version.

Yep, and that's sad.

**Comment by Nattfarinn** [comment]
It's called progress :)

**Comment by emodric** [comment]
It's called not caring for your community.

**Comment by pspanja** [comment]
What are your plans for UGC then?

**Comment by MarioBlazek** [comment]
A better solution in the future? When? You've removed information collection tables, now doing this, what else can we expect?

**Comment by alongosz** [comment]
> It's called not caring for your community.

We DO care about You. Supporting everything in every possible version is very bad practice (leads to "spaghetti code"). We see it also as an opportunity for our Partners to improve their own code as well :-)

**Comment by Nattfarinn** [comment]
> It's called not caring for your community.

That's serious accusation. :) We do care very much about community and we have feedback people are very happy in the direction the project is now going. Also we do not force anyone to upgrade ASAP. 2.5 is LTS and will be supported for years from now, so just take your time, update whatever is necessary and release new bundle versions. :)

**Comment by emodric** [comment]
> Supporting everything in every possible version is very bad practice

Nobody is saying you should support everything in every possible version. BUT, 2.5 LTS SHOULD be compatible with 3.0, just how Symfony x.4 LTS is compatible with the whole (x+1).y branch. It makes 3rd party bundles easier to maintain AND it makes upgrades to newer versions easier and cheaper, both for developers and clients.

> That's serious accusation. :)

Yes, it serious, and it was not done lightly. Unfortunately, eZ decisions as of late give it a lot of weight.

**Comment by wizhippo** [comment]
> A better solution in the future? When? You've removed information collection tables, now doing this, what else can we expect?

This is a concern I've had from legacy to ezplatform and voiced before.  Leaves the community with a bad feeling when past functionality is removed and replaced by a paid option (info collectors/pages),  I understand ez needs to make money and deserves to.  But losing functionality which had existed will always leave some resentment.

I'll get over it at some point as I still believe ez is a great platform.  Perhaps being more open and including the community in the planning for the future of UGC could help us get excited and understand the reasons for changes.

**Comment by Nattfarinn** [comment]
> This is a concern I've had from legacy to ezplatform and voiced before. Leaves the community with a bad feeling when past functionality is removed and replaced by a paid option (info collectors/pages), I understand ez needs to make money and deserves to. But losing functionality which had existed will always leave some resentment.

Totally understand. Some decisions are just business decisions and I don't feel competent to fully address this concern, but we will definitely provide UGC as a separate feature. We just don't feel like exposing admin related forms outside of admin is the best way.

But, you are still able to do that if you want, this PR mostly makes Repository Forms part of Admin namespace, without stripping it from any existing functionalities.

Major version release is the only time window we're able to make such BC changes and to prepare codebase for future improvements. It will make upgrade more complicated but we're doing our best to make it worth it. :)

**Comment by wizhippo** [comment]
> but we will definitely provide UGC as a separate feature.

Looking forward to it as this is very needed.  Manipulating repo forms is always a struggle and feels wrong (guess it should if it's original intention was just for admin ui)

**Comment by webhdx** [comment]
Closed in favor of #1120. We heard you and we decided to change the plans slightly. Please refer to #1120 for more  info on partial backwards compatibility.

**Pull request closed without merging**
