### PR TITLE
EZP-29322: As an editor I want to use translated Admin panel

### PR DESCRIPTION
**Pull request by mikadamczyk**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29322
| Bug fix?      |no
| New feature?  | yes
| BC breaks?    |no
| Tests pass?   | yes
| Doc needed?   |no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Refers to https://github.com/ezsystems/ezpublish-kernel/pull/2361

screen shot 2018-06-22 at 2 58 13 pm

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by lserwatka** [comment]
@bdunogier ping

**Comment by mikadamczyk** [comment]
@bdunogier Is any chance to rename translation file name to the same as in symfony, for example from bookmark.de_DE.xlf to bookmark.de.xlf. It is a problem when browser send accept language as ‘no’ for ‘bn_no’ or ‘el’ for ‘el_GR’. So far this is the only solution I have.

**Comment by bdunogier** [comment]
It will require some work & research, @mikadamczyk, but I think that we need to do this, indeed.

**Comment by bdunogier** [comment]
The request listener looks good.

Maybe I would remove the `preg_match` part. Instead, we could modify the kernel's translation loader so that it registers translations using the language code instead of the language + region. This part belongs in the kernel rather than in the admin, as the frontend uses translation as well.

What do you think ?

**Comment by bdunogier** [comment]
I agree about changing files names. But I also think it is too late so close from release. I'm only suggesting that instead of doing that in `AvailableTranslationPass`, we do it in the `TranslationCollectorPass`, that's all.

Also, what would we change them to ? The issue you mention about `fr_ca` is very valid. But it applies to renaming files & treating locales the way you did here. As far as crowdin.com is concerned, French is `fr`, and the other variants are regional (`fr_ca`, `fr_be`...).

For now, unless we decide to remove the translation files AND packages before friday, we should do the renaming when collecting the files, using a pass of some sort.

**Comment by mikadamczyk** [comment]
First we must merge https://github.com/ezsystems/ezpublish-kernel/pull/2361

**Pull request merged**
