### PR TITLE
EZP-29316: Only show add/remove buttons for urls if policy allows

### PR DESCRIPTION
**Pull request by wizhippo**
| Question      | Answer
| ------------- | ---
| Tickets       | [EZP-29316](https://jira.ez.no/browse/EZP-29316)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Urls should only allow add/remove urls if policy allows

screen shot 2018-06-20 at 3 27 00 pm

screen shot 2018-06-21 at 8 50 43 am

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by SylvainGuittard** [comment]
Thanks @wizhippo for the contribution.
Is this PR related to this user story https://jira.ez.no/browse/EZP-29225?

**Comment by wizhippo** [comment]
@SylvainGuittard I can't access the document but it look like it is,

**Comment by mikadamczyk** [comment]
@SylvainGuittard yes this PR is related to https://jira.ez.no/browse/EZP-29225

**Comment by SylvainGuittard** [comment]
Thanks @mikadamczyk for the confirmation and for helping on this!
I think we can still have this feature on 2.2, right?

**Comment by lserwatka** [comment]
@SylvainGuittard yes

**Pull request merged**
