### PR TITLE
EZP-28497: RelationList field type issues

### PR DESCRIPTION
**Pull request by sunpietro**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28497
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

**Requires:**
- https://github.com/ezsystems/repository-forms/pull/186

**Bugfixes for:**
- [x] Cannot select content when no limit is set,
- [x] Limit message is visible when no limit is set,
- [x] Cannot select a content when no content type restriction is set,
- [x] Cannot reorder related content in the edit mode,
- [x] The trash button should be disabled when no checkbox is selected,
- [x] Setting a default location in the content type edit.

### CODE REVIEW

**Comment by lserwatka** [comment]
@mnocon can we merge this one? Have you tested it?

**Comment by mnocon** [comment]
@lserwatka there's one thing to add here (updating the displayed Default location after selecting one), otherwise all looks good.

**Comment by lserwatka** [comment]
OK, @sunpietro are on it already?

**Comment by lserwatka** [comment]
Thank you @sunpietro & @mnocon 👍

**Pull request merged**
