### PR TITLE
EZP-30802: Fixed OE JS error in case of missing element path

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
| Question      | Answer
| ------------- | ---
| Tickets       | [EZP-30802](https://jira.ez.no/browse/EZP-30802)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Steps to reproduce:

1. Start to create any content with Richt Text field.
2. In Online Editor add any custom tag
3. Set "Right" align for added custom tag
4. Remove an empty paragraph above the custom tag (using trash icon)
5. Click on the area in Online Editor left to the custom tag

You will get following JavaScript error in the console:
```
TypeError: Cannot read property 'lastElement' of null
```

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by SerheyDolgushev** [comment]
Seems like a good scenario to reproduce the issue was picked up. So there is another JavaScript error after this commit:
```
TypeError: Cannot read property 'elements' of null
```

**Comment by SerheyDolgushev** [comment]
Please note, all JavaScript errors seem to be fixed now. But there are still some issues with positioning "ez-add" button. In the described scenario the button sticks at the top of the window. After spending a few hours on trying to fix it, we realized we need help from Online Editor developers here.
Please feel free to complete this PR.

**Comment by SerheyDolgushev** [comment]
@alongosz please have a look here.

**Comment by SylvainGuittard** [comment]
@dew326 and @tischsoic Could you please have a look? Thanks

**Comment by dew326** [comment]
I quickly checked the issue and don't have any good solution for that.
The problem is that after a click on the left none of the elements has focus.

**Comment by SerheyDolgushev** [comment]
@dew326 in this case, maybe it worth to merge this PR, just to get rid of JavaScript error. And create have a separate task about correct positioning for `ez-add` toolbar?

When I was trying to fix it, I was able to set the correct top offset for the plus button. But the buttons which are showing up that plus button is clicked had zero top offset.

**Comment by dew326** [comment]
Is this happen only when there is one custom tag and nothing else? If so we could set the position to the middle of the richtext area (or to the top). I know this is not the best solution but for me sounds okish.

**Comment by SerheyDolgushev** [comment]
Sorry, not sure, but there might be some other strange scenarios when the elements path is missing.
Even if `ez-add` has the wrong position - it is still better than JavaScript error which breaks the Online Editor.

**Comment by dew326** [comment]
I totally agree that misplaced button is better than breaking AE and be forced to refresh the page.

**Comment by dew326** [comment]
I added a commit where add button is moved to the top of a richtext area when the path is missing. 

@tischsoic please do a review

**Comment by dew326** [comment]
@katarzynazawada fixed

**Comment by lserwatka** [comment]
@mikadamczyk could you merge it up?

**Comment by mikadamczyk** [comment]
@lserwatka done

**Pull request merged**
