### PR TITLE
EZP-28939: Internal Server Error when saving unpublished Draft

### PR DESCRIPTION
**Pull request by webhdx**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28939
| Requires | https://github.com/ezsystems/repository-forms/pull/227
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes/no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by webhdx** [comment]
Keep in mind it relies on https://github.com/ezsystems/repository-forms/pull/227

**Comment by micszo** [comment]
I encountered the same issue on my installation.

**Comment by webhdx** [comment]
@micszo @m-tyrala Fixed.

**Comment by micszo** [comment]
@webhdx hope this is just me but now I get:
> An exception has been thrown during the rendering of a template ("Could not find 'VersionInfo' with identifier 'array ( 'contentId' => 1, 'versionNo' => 1, )'"). [in vendor/ezsystems/ezplatform-admin-ui/src/bundle/Resources/views/content/content_edit/content_edit.html.twig:68]

**Comment by m-tyrala** [comment]
On my EE installation all works fine, I'll also check P, just to be sure.

**Comment by micszo** [comment]
Indeed it occurs only on pure Platform.

**Comment by m-tyrala** [comment]
I confirm - there's still problem in Platform.

**Comment by webhdx** [comment]
Thanks for heads up. I've fixed it already. @m-tyrala @micszo

**Pull request merged**
