### PR TITLE
EZP-30961 - Toolbar missed after using navigation path and embed

### PR DESCRIPTION
**Pull request by ITernovtsiy**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-30961
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

STR:
1) Open editor
2) add embed object and select it
3) click on item in the navigation path

AR: JS error in console, toolbar not appearing at all (even after further clicks in editor) 
ER: No error returned

video attached in JIRA ticket

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by dew326** [comment]
Hi @ITernovtsiy,
I cannot reproduce your issue. It works with the provided steps. When I watch your video I'm wondering how did you add Embed Image to the table because we do not have such a feature.
Could you provide more detailed steps?

**Comment by ITernovtsiy** [comment]
Hi @dew326 
It's not only with tables, you can use custom tag content to reproduce it. Uploading a new video to JIRA ticket.

p.s. _regarding embed in table, we have embed images from content migrated from legacy, it's not related to this bug_

**Comment by dew326** [comment]
Sorry I still cannot reproduce the issue. But on the new video, I spot one difference in the path. I have `Custom Tag > p > Embed Inline` and this is the proper path, but you have `div > p > Embed Inline` for some reason your custom tag is not detected as a custom tag and probably this is the root of the issue.

**Comment by ITernovtsiy** [comment]
Hm, you're correct, there is a bug when "div" appearing in path. Attached video of how I got a div instead of "Custom Tag". Weird, but I can't reproduce it locally, only on production.

**Comment by ITernovtsiy** [comment]
Sorry, my fault. The issue caused by chrome plugin (Grammarly). Can be closed.

**Pull request closed without merging**
