### PR TITLE
EZP-29902: Admin UI - Locale is not correctly set

### PR DESCRIPTION
**Pull request by mikadamczyk**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29902
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    |no
| Tests pass?   | yes
| Doc needed?   |no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

screen shot 2018-12-17 at 12 56 16 pm

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by lserwatka** [comment]
@mikadamczyk does it affect 1.3 branch?

**Comment by mikadamczyk** [comment]
@lserwatka yes, I changed base

**Comment by lserwatka** [comment]
OK, then you must rebase with 1.3 now, so PHPUnit can pass.

**Comment by m-tyrala** [comment]
That should do the trick once and for all, let's wait for travis tests results.

**Comment by Plopix** [comment]
Install the `1.3.x-dev` on my test env where I found the issue and I can confirm the fix as well.

Well done guys! You rock!

**Pull request merged**
