### PR TITLE
EZP-28339: Add custom theming following guidelines for user create/edit

### PR DESCRIPTION
**Pull request by webhdx**
| Question      | Answer
| ------------- | ---
| Requires    | https://github.com/ezsystems/repository-forms/pull/145
| Tickets       | https://jira.ez.no/browse/EZP-28339
| Bug fix?      |no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review
- [ ] Rebase to `master` after QA is done

### CODE REVIEW

**Comment by webhdx** [comment]
@m-tyrala @barbaragr This PR can be tested as I don't see anything smaller which is ready for QA. I rebased this PR so that you are also testing #45 as these PRs are related. Keep in mind that you also need ezsystems/repository-forms#145.

**Comment by barbaragr** [comment]
1. There is default validation like in the picture below. Shouldn't be here a message with red font that field is required?

**Comment by barbaragr** [comment]
1. There is default validation like in the picture below. Shouldn't be here a message with red font that field is required?
screen shot 2017-11-30 at 12 29 59
When I do the steps:
a. Go to user/create
b. Don't fill anything, just click publish, there is a validation only for the first empty field. 

2. Ezimage doesn't work for adding a new user - I cannot upload any image by button or drag and drop.

3. Cancel button doesn't work:
a. Go to user/create
b. Don't fill anything, just click cancel - there is a validation for the first empty field and nothing more happens.

4. When I add a new user which belongs to user, not to any user group (breadcrumb: Users/my_user), when I try to log in to this account there is 403 error. I understand why, but maybe we could inform a user that he has no rights in more friendly way?

**Comment by barbaragr** [comment]
5. If I add user as an editor I cannot go to content structure:
a. Go to Users/Editors and click create
b. Fill required fields and publish
c. Log in using credentials of user from previous step
d. go to content/content structure - there is error 500

6. Problem with sending user to trash and restoring
a. Go to Users/Editors
b. Create here two users: user1 and user2
c. Move to trash user2
d. Go to trash and restore user2
e. log out and try to log in using credentials from user2 - there is 403 error
f. log in as admin and go to Users/Editors - list of sub-items is empty, console shows:
screen shot 2017-11-30 at 13 21 28
When you use Search and type: user1 there are some results and it shows that user1 exists and is located in Users/Editors, you can also log in as user1. For user2 there are no search results .

**Comment by barbaragr** [comment]
7. Unable to log in 
a. Create content type with field type ezuser (not required)
b. Go to Content/content structure and click create
c. choose the content type with ezuser
d. fill all fields and publish - it's impossible to log in with this credentials. But if you add this content item in location for example: Users/Administration Users there is no problem to log in.

8. User added with content type with ezuser is not visible in roles assignment
a. Create content type with field type ezuser (not required)
b. Go to Content/content structure or Users/Admianistration users and click create
c. choose the content type with ezuser
d. fill all fields and publish
e. go to Admin/Roles and click on Assign to Users/Groups
f. In table Users and Groups/User user from previous step is not visible. But when it's created in folder Users/Administration user it seems that it has this role assigned.

9. Field type ezuser cannot be checked as searchable, so users added by content type with ezuser cannot be found unlike the users added from Admin/Users/.../Create

10. Errors when ezuser is not required
a. Create content type with field type ezuser (not required)
b. Go to Users/Admianistration users and click create
c. choose the content type with ezuser
d. Fill nothing, just click publish - BadRequestHttpException: Argument 'login' is invalid: 'NULL' is wrong value in class 'UserCreateStruct' It behaves that way for empty username, password and e-mail

11. Validation message for invalid password
a. Create content type with field type ezuser (not required)
b. Go to Users/Admianistration users and click create
c. choose the content type with ezuser
d. fill username, password and e-mail
e. click publish - the validation message should be consistent with others - red font etc. and please make a space between ":" and "This"
screen shot 2017-11-30 at 15 59 34

**Comment by barbaragr** [comment]
12. Console bug when I go to create using content type with ezuser
a. Create content type in Admin/Content types/Content/, add only ezuser field type, marked it as required.
b. go to creating and choose added content type - when creating form is shown, console shows: 
>GET http://192.168.56.53/js/7853bf8_part_7_ezuser_18.js net::ERR_ABORTED
 
13. Broken dashboard
Preconditions: created content type in Admin/Users, content name pattern: "user", one field type added - ezuser with id: "user", required.
a. Login as admin
b. Go to Users/Administration users and click create
c. Choose content type from preconditions
d. Fill the form and click publish
e. Log in to the new admin user account
f. Click Content and then Content structure
g. Click Create and choose content type from preconditions
h. Fill the form and click publish
i. Try to log in to the new user account - error " User 'porkypig' doesn't have user/login permission to SiteAccess 'admin'" 
j. Go to url: ../admin/login and try to log in with credentials of admin user from steps b-d  - there is another exception (on URL: ../admin/dashboard ): "An exception has been thrown during the rendering of a template ("Argument '$fieldIdentifier' is invalid: 'first_name' field not present on content #53 'duffyduck'")." and "Argument '$fieldIdentifier' is invalid: 'first_name' field not present on content #53 'duffyduck'" When I change the URL for ../admin it works fine.
k. Log out and log in with regular admin - there is still on ../admin/dashboard error from previous user: "An exception has been thrown during the rendering of a template ("Argument '$fieldIdentifier' is invalid: 'first_name' field not present on content #53 'duffyduck'").
Console error: 
screen shot 2017-12-01 at 11 42 50

**Comment by webhdx** [comment]
1. Frontend validation is not working. @sunpietro is on it.
2. As above.
3. Fixed.
4. This is related to the Roles. You have to properly set up your permissions. As for now setting permissions only works for users created from ContentType named 'user' and assigned to the location which has 'user_group' ContentType. Can you open separate ticket for this? I'm aware of the issue and I will fix it with @alongosz.
5. Permissions. See above.
6. @sunpietro this one is caused by UDW and subitems. I noticed that after restoring content from trash it gets new ContentID but for some reason JS is still trying to fetch old ones.
7. Permissions. See above.
8. See 4. This has to be fixed separately as the fix has to be done on ezpublish-kernel as well.
9. User fieldtype is not searchable. If you want your user to be visible in search results add Searchable field for name and last name.
10. It's now validated but frontend validation is needed as well (ping @sunpietro)
11. Frontend validation is broken.
12. I couldn't reproduce the issue but it looks like you have problems with assetic. Did you try `bin/console assetic:dump`?
13. Permissions issue. I couldn't reproduce second part of the problem.

@barbaragr  Did you test user edit feature?

**Comment by barbaragr** [comment]
Thanks for the answers. Yes' I've tested edit mode, but I will retest all after fixing the issues, so I'm waiting for @sunpietro.

**Comment by sunpietro** [comment]
@barbaragr 

2. it's correct as per design from https://jira.ez.no/browse/EZP-27910

**Comment by barbaragr** [comment]
2. When ezuser is required and one of the fields (for example Username) is empty and lost focus, only this field should have red background. 
screen shot 2017-12-06 at 13 34 44

**Comment by barbaragr** [comment]
3. Empty username field after copying a user
Steps:
a. Go to Admin/Users/Administrator users
b. Choose Administrator User from sub-items
c. From right bar menu click "Copy"
d. select location, for ex. eZ platform and confirm
e. go to edit mode of the copied item - username is empty and it's readonly so it's impossible to fill it or make changes in whole item, because when you want to publish, validation message is shown that username is empty.

**Comment by lserwatka** [comment]
rebase is needed here

**Pull request merged**
