### PR TITLE
EZEE-2016: Fix date/time format on Dashboard & Link manager

### PR DESCRIPTION
**Pull request by tischsoic**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZEE-2016
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | -
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Fixes date format.

#### Checklist:
- [ ] ~Coding standards (`$ composer fix-cs`)~
- [x] Ready for Code Review

### CODE REVIEW

**Comment by dew326** [comment]
Link Manager also has incorrect dates.

**Comment by tischsoic** [comment]
Ping @dew326 - fixed dates in link manager.

**Comment by dew326** [comment]
I think this should go to 1.2

**Comment by tischsoic** [comment]
@barbaragr fixed :)

**Comment by tischsoic** [comment]
Merged up.

**Pull request merged**
