### PR TITLE
IBX-662: Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null at setContainerHeight

### PR DESCRIPTION
**Pull request by GrabowskiM**
| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-662
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Review by lucasOsti — APPROVED** [review]

**Review by dew326 — APPROVED** [review]

**Review by tischsoic — APPROVED** [review]

**Comment by bogusez** [comment]
@GrabowskiM cannot publish later content "Landing page"

`Uncaught TypeError: Cannot read property 'removeAttribute' of null at focusOnFirstError`

Screenshot 2021-06-28 at 14 47 54

**Comment by GrabowskiM** [comment]
That's a different one bug, not connected with the one this PR fixes. Could you create new jira issue for this one? I'll try to look at it.

**Comment by bogusez** [comment]
> That's a different one bug, not connected with the one this PR fixes. Could you create new jira issue for this one? I'll try to look at it.

Yes, sure. I will report a new task.

**Comment by dew326** [comment]
Also, this console error doesn't prevent from publishing content. You have not filled fields "title" and "description".

**Review by bogusez — APPROVED** [review]

**Comment by lserwatka** [comment]
You can merge it up now.

**Comment by GrabowskiM** [comment]
done

**Pull request merged**
