### PR TITLE
[Behat] Added filtering of Content Types in Content Type Picker

### PR DESCRIPTION
**Pull request by mnocon**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31816
| Bug fix?      | fix in tests
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Failing build:
https://travis-ci.com/github/ezsystems/ezcommerce-shop/jobs/382898056
https://res.cloudinary.com/ezplatformtravis/image/upload/v1599678529/screenshots/5f5928412ddd5480454420-vendor_ezsystems_ezplatform-admin-ui_features_standard_contenttypefields_feature_42_psujmy.png
```
      | ezrichtext           | Rich text                    |                                                                       | value     | Lorem ipsum dolor sit                                                     |            |                       |         |             | Lorem ipsum dolor sit     |

        Exception: element click intercepted: Element is not clickable at point (1142, 966)

          (Session info: chrome=80.0.3987.149)

          (Driver info: chromedriver=80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=Linux 4.4.0-101-generic x86_64) in vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:144

        Stack trace:
        #0 vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory()
        #1 vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(218): WebDriver\AbstractWebDriver->curl()
        #2 vendor/instaclick/php-webdriver/lib/WebDriver/Container.php(234): WebDriver\AbstractWebDriver->__call()
        #3 vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(799): WebDriver\Container->__call()
        #4 vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(787): Behat\Mink\Driver\Selenium2Driver->clickOnElement()
        #5 vendor/friends-of-behat/mink/src/Element/NodeElement.php(153): Behat\Mink\Driver\Selenium2Driver->click()
        #6 vendor/ezsystems/ezplatform-admin-ui/src/lib/Behat/PageElement/ContentTypePicker.php(29): Behat\Mink\Element\NodeElement->click()
        #7 vendor/ezsystems/ezplatform-admin-ui/src/lib/Behat/PageObject/ContentItemPage.php(62): EzSystems\EzPlatformAdminUi\Behat\PageElement\ContentTypePicker->select()
        #8 vendor/ezsystems/ezplatform-admin-ui/src/lib/Behat/BusinessContext/ContentViewContext.php(38): EzSystems\EzPlatformAdminUi\Behat\PageObject\ContentItemPage->startCreatingContent()
        #9 [internal function]: EzSystems\EzPlatformAdminUi\Behat\BusinessContext\ContentViewContext->startCreatingContent()
```

Looks like Selenium was not able to handle clicking the selected item, I've added usage of the filter feature of Content Type Picker to make it more robust.

### CODE REVIEW

**Comment by micszo** [comment]
Needed only for master? :)

**Comment by mnocon** [comment]
Yep, I've never seen error like this on lower branches, I guess it's related to redesign.

**Comment by micszo** [comment]
Could we leave the backport for later? If the approach serves its purpose.

**Comment by mnocon** [comment]
Sure, works for me 😄

**Review by micszo — APPROVED** [review]

**Comment by mnocon** [comment]
@micszo sorry for trouble, but I had an epiphany and had to add a new commit: https://github.com/ezsystems/ezplatform-admin-ui/pull/1478/commits/71d9b17bf8aef55900f305d2a43cd74ff0752f86

**Review by bogusez — APPROVED** [review]

**Review by bogusez — APPROVED** [review]

**Pull request merged**
