### PR TITLE
EZP-29877: Custom tags and nested table focus issue

### PR DESCRIPTION
**Pull request by dew326**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29877
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by lserwatka** [comment]
@dew326 could you re-base with master, so that PHPUnit can pass?

**Comment by dew326** [comment]
@lserwatka done

**Comment by lserwatka** [comment]
@mnocon @m-tyrala Behat is failing here, any idea?

**Comment by m-tyrala** [comment]
I'm checking it

**Pull request merged**
