### PR TITLE
EZP-31875: Added request matcher to recognize REST requests executed in AdminUI context

### PR DESCRIPTION
**Pull request by kmadejski**
| Question      | Answer
| ------------- | ---
| Tickets       | [EZP-31875](https://jira.ez.no/browse/EZP-31875)
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes/no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

This PR introduces a `RequestMatcher` that is needed for https://github.com/ezsystems/ezplatform-rest/pull/54.

I'm happy to change the class name if someone has any better ideas. 

#### Checklist:
- [X] Coding standards (`$ composer fix-cs`)
- [X] Ready for Code Review

### CODE REVIEW

**Comment by bdunogier** [comment]
I suggest you change the commit and PR's descriptions to match what that specific PR actually does (e.g. add a REST + Admin request matcher). It can easily get confusing in changelogs. The code itself should probably not refer to JWT either.

**Review by adamwojs — APPROVED** [review]
+1 but we are missing unit tests coverage.

> The code itself should probably not refer to JWT either.

Agree with @bdunogier, matcher could be used in other scenarios as well :wink:

**Comment by lserwatka** [comment]
@kmadejski we need to add tests as well

**Comment by alongosz** [comment]
> This PR introduces a RequestMatcher that is needed for ezsystems/ezplatform-rest#54.

@kmadejski Could you elaborate on that? What does it do?
AFAIK REST has an independent context / routes so not sure why admin context would ever be present there. But I'm probably missing the function here.

**Comment by adamwojs** [comment]
> [**@kmadejski**](https://github.com/kmadejski) Could you elaborate on that? What does it do?  
> AFAIK REST has an independent context / routes so not sure why admin context would ever be present there. But I'm probably missing the function here.

@alongosz See https://github.com/ezsystems/ezplatform-rest/pull/54#issuecomment-693274969

**Comment by alongosz** [comment]
Ok, +1 once test coverage is present.

**Comment by kmadejski** [comment]
@alongosz / @webhdx / @ViniTou - added tests, everything is green. Could you please do a final review?

**Review by alongosz — APPROVED** [review]

**Pull request merged**
