### PR TITLE
EZP-27934: Remove CacheService now that spi cache got fix

### PR DESCRIPTION
**Pull request by andrerom**
> Issue: https://jira.ez.no/browse/EZP-27934

### CODE REVIEW

**Comment by lserwatka** [comment]
@andrerom could share a ticket where this was fixed in kernel? This is great news.

**Comment by andrerom** [comment]
@lserwatka Handled it as part of this issue as it was a bit of mix of everything, and as 7.0 kernel is still rebased for clean history until first public beta release. But the kernel change was addtiona of these lines: https://github.com/ezsystems/ezpublish-kernel/blob/7.0/eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php#L242-L244

**Comment by lserwatka** [comment]
@Nattfarinn I think we can merge this one.

**Comment by Nattfarinn** [comment]
(Removing ezrobot complain about coding standards, as it's fixed on master already)

**Pull request merged**
