### PR TITLE
EZP-31321: Dropped injecting zero-width space into ezembed(inline) elements

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
| Question      | Answer
| ------------- | ---
| Tickets       | [EZP-31321](https://jira.ez.no/browse/EZP-31321), related to [EZP-29882](https://jira.ez.no/browse/EZP-29882)
| Requires | ezsystems/ezplatform-richtext#88
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Parent PR: https://github.com/ezsystems/ezplatform-richtext/pull/88.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by SerheyDolgushev** [comment]
Zero width space seems to also cause some issues with Solr indexing:
```
org.apache.solr.common.SolrException: Illegal character ((CTRL-CHAR,&#8203; code 14))
```

**Comment by lserwatka** [comment]
@alongosz @adamwojs could you have a final look on this one?

**Comment by lserwatka** [comment]
@dew326 could you merge it up?

**Comment by dew326** [comment]
@lserwatka done

**Pull request merged**
