### PR TITLE
IBX-580: Added deleted location limitation role access scenario

### PR DESCRIPTION
**Pull request by micszo**
| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-580](https://issues.ibexa.co/browse/IBX-580)
| Bug fix?      | no
| New feature?  | no (new test case)
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Test checking whether it is possible to access a role that has a policy with a location limitation pointing to a location that has been deleted.

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [ ] Ready for Code Review

### CODE REVIEW

**Comment by micszo** [comment]
PR for 3.3: https://github.com/ezsystems/ezplatform-admin-ui/pull/1800

**Review by mnocon — COMMENTED** [review]
The whole Scenario is run as admin, maybe it should not be added to the personas suite and should in included in the Roles.feature file?

Something like:
```
    Given I create "folder" Content items in root in "eng-GB"
      | name            | short_name      |
      | DeletedLocation | DeletedLocation |
    And I create a role "DeletedLocationRole"
    And I add policy "content" "read" to "DeletedLocationRole" with limitations
      | limitationType | limitationValue  |
      | Location       | /DeletedLocation |
    And I send "/DeletedLocation" to the Trash
    When I am logged as "admin"
    And I go to "Roles" in "Admin" tab
    And I go to "DeletedLocationRole" "Role" page
    Then I should be on "Role" "DeletedLocationRole" page
```
_should_ work and does not need to be split into two phases (setup & execution).

**Comment by micszo** [comment]
> The whole Scenario is run as admin, maybe it should not be added to the personas suite and should in included in the Roles.feature file?
> 
> Something like:
> 
> ```
>     Given I create "folder" Content items in root in "eng-GB"
>       | name            | short_name      |
>       | DeletedLocation | DeletedLocation |
>     And I create a role "DeletedLocationRole"
>     And I add policy "content" "read" to "DeletedLocationRole" with limitations
>       | limitationType | limitationValue  |
>       | Location       | /DeletedLocation |
>     And I send "/DeletedLocation" to the Trash
>     When I am logged as "admin"
>     And I go to "Roles" in "Admin" tab
>     And I go to "DeletedLocationRole" "Role" page
>     Then I should be on "Role" "DeletedLocationRole" page
> ```
> 
> _should_ work and does not need to be split into two phases (setup & execution).

Applied in 3c577d8.

**Review by mnocon — APPROVED** [review]
Looks great, thanks!

**Comment by micszo** [comment]
PR to 3.3 (https://github.com/ezsystems/ezplatform-admin-ui/pull/1800) is now updated. Please have a look.

**Pull request merged**
