### PR TITLE
IBX-241: Subitems - priority buttons hidden behind most-right column

### PR DESCRIPTION
**Pull request by lucasOsti**
| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/IBX-241
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Review by tischsoic — APPROVED** [review]

**Review by dew326 — APPROVED** [review]

**Comment by micszo** [comment]
Hi. Should base be _master_ or _2.3_? JIRA ticket mentions 3.3.0.
Or even further - is 3.2 affected?

**Comment by piotrbisaga** [comment]
@lucasOsti I reproduced it on 3.2, could you please change base to 2.2?

**Comment by piotrbisaga** [comment]
QA approved.
Check on both Ibexa Commerce 3.2 & 3.3, safari, chrome and mozilla tested.

**Comment by adamwojs** [comment]
Could you please merge up changes @lucasOsti ?

**Comment by lucasOsti** [comment]
> Could you please merge up changes @lucasOsti ?

done

**Pull request merged**
