### PR TITLE
EZP-26238: eZPlatform login screen redirecting to the link the user entered initially

### PR DESCRIPTION
**Pull request by ViniTou**
| Question      | Answer
| ------------- | ---
| Tickets       | 
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no?
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review
- [ ] Update metarepo with https://github.com/ezsystems/ezplatform/pull/272

### CODE REVIEW

**Comment by lserwatka** [comment]
@m-tyrala @ViniTou Behat is failing here. Can you have a look here?

**Comment by m-tyrala** [comment]
@lserwatka @ViniTou at the moment, Authentication tests expects that after login we're on Dashboard page, but it's no longer truth.

**Comment by lserwatka** [comment]
I guess this requires change in meta repo.

**Comment by m-tyrala** [comment]
Ok, i tested this PR, all seems to be right, but when we log in directly from /admin (without any previous redirections), then after logging in we are on Content Structure > Home (that is the cause of behat failed test). Shouldn't we go to Dashboard in that case? As it is the main page of the app?

**Comment by ViniTou** [comment]
@m-tyrala 
I discussed this issue with @lserwatka and we decided that this going to stay this way (at least for now).

**Pull request merged**
