### PR TITLE
EZP-28605: Change link to edit CT draft on search result

### PR DESCRIPTION
**Pull request by mikadamczyk**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28605
| Bug fix?      |no
| New feature?  | yes
| BC breaks?    |no
| Tests pass?   | yes
| Doc needed?   |no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Change link to edit CT draft on search result. Also may affect restoring Archived versions in Versions tab in CT.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by lserwatka** [comment]
@mikadamczyk rebase is needed here

**Comment by webhdx** [comment]
This is potentially destructive - did you check how does it work on Content View page where SIL and Edit widgets are using 2 content edit forms?

**Comment by lserwatka** [comment]
It should be similar as in the Sub-Items List

**Comment by mikadamczyk** [comment]
Rebase done

**Pull request merged**
