### PR TITLE
EZP-28217: Add Object State tab to location view

### PR DESCRIPTION
**Pull request by wizhippo**
JIRA: https://jira.ez.no/browse/EZP-28217

This adds a tab to view the content object state

### CODE REVIEW

**Comment by lserwatka** [comment]
Hey @wizhippo, thank you for your contribution. I'm curious about your developer experience. Do you mind to drop me a private message with your feedback?

**Comment by SylvainGuittard** [comment]
Hi @wizhippo!
Thanks for the contribution. 🎉  
Could you please add a screenshot to the description?

**Comment by wizhippo** [comment]
@SylvainGuittard I'm assuming you mean in Jira?

**Comment by wizhippo** [comment]
@lserwatka Sure.  I so have one question though.  What is the correct way to update the translations?

**Comment by SylvainGuittard** [comment]
@wizhippo I was thinking about the description of the PR, but JIRA is fine. Thanks :)

**Comment by inakijv** [comment]
Hi @wizhippo thank you for this contribution. We would like to know more about it :smile:

**Comment by lserwatka** [comment]
@inakijv A screen shot was added to the JIRA ticket https://jira.ez.no/browse/EZP-28217 I think it is self explanatory. It only prints object states related information.

**Comment by SylvainGuittard** [comment]
Thanks @wizhippo for moving the table to the `Details` tab. 👍

**Comment by lserwatka** [comment]
@wizhippo could you re-base with master?

**Comment by wizhippo** [comment]
@lserwatka re-based.

**Comment by lserwatka** [comment]
@wizhippo thank you, looks like there is still conflict on translations. Could you resolve it?

**Comment by andrerom** [comment]
Nice @wizhippo :)

**Pull request merged**
