### PR TITLE
[EZP-28776] Harmonize hover & active states for creating and editing …

### PR DESCRIPTION
**Pull request by inakijv**
Harmonize hover & active states for creating and editing content

| Question      | Answer
| ------------- | ---
| Tickets       | [EZP-28776](https://jira.ez.no/browse/EZP-28776)
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Most important aspects:
- Currently in V.2.0.0 when the user creates or edits any given content item hover & focus, as well as active states are not harmonized with the states defined (see UDW's, for instance).
- Current PR corrects this also in order to improve usability due to a not proper color contrast solution defined.

create_hover_state
create_active_state
edit_hover_state
edit_active_state

#### Checklist:
- [ ] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

### CODE REVIEW

**Comment by lserwatka** [comment]
I changed branch to 1.0.

**Comment by lserwatka** [comment]
@inakijv could you rebase with 1.0 branch, looks like your PR was made from master.

**Comment by lserwatka** [comment]
We should not change composer.json in this PR.

**Comment by lserwatka** [comment]
@dew326 @sunpietro could we take over on this PR. It is a low hanging fruit for 2.0.2 release anytime soon.

**Comment by sunpietro** [comment]
I'm gonna take this one over.

**Comment by sunpietro** [comment]
Closing in favor of https://github.com/ezsystems/ezplatform-admin-ui/pull/331

**Pull request closed without merging**
