### PR TITLE
EZP-29897: Workflow state panel becomes unusable in the Content Edit, when its container is displayed below the fold

### PR DESCRIPTION
**Pull request by sunpietro**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29897
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Tests pass?   | yes/no
| Doc needed?   | yes/no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

## Issues fixed
- [x] panel hiding below the fold so user is not able to submit the content of a panel (test it with workflow feature and small window height),
- [x] click outside of a panel detection

### CODE REVIEW

**Comment by lserwatka** [comment]
@sunpietro you will have to rebase after https://github.com/ezsystems/ezplatform-admin-ui/pull/755 is merged. So that we can have green tests here.

**Comment by sunpietro** [comment]
@lserwatka ok, I'll wait for merge then.

**Comment by lserwatka** [comment]
@sunpietro you can rebase now with 1.3. PHPUnit should be passing again.

**Comment by sunpietro** [comment]
Done

**Comment by lserwatka** [comment]
@sunpietro you can merge it up.

**Comment by sunpietro** [comment]
Done

**Pull request merged**
